<template lang="pug">
section#clippy
  #clip-holder(:class="shown ? 'introduction' : 'exiting'")
    img#the-clipman-himself(src="https://s3-us-west-2.amazonaws.com/s.cdpn.io/522641/coppy.svg")
  #clippy-modal(v-show="clipMessage" :class="shown ? '' : 'exiting'")
    p {{clipMessage}}

</template>

<script>
export default {
  name: 'NotClippy',   
  data() {
    return {
      shown: false,
      clipMessage: ""
    }
  },
  mounted(){
    console.log('echo')
    this.$emit('clipLoad')
  },
  methods:{
    showClippy(duration = 9000, showMessage, leaveMessage){
      this.shown = true
      console.log('showMessage', duration, showMessage, leaveMessage)
      this.clipMessage = showMessage
      setTimeout(() => {
        this.clipMessage = showMessage;
        setTimeout(() => {this.dismissClippy(leaveMessage)}, Math.max(0, duration-1000));
      }, 1000);
    },
    setClippyMessage(message){
      this.clipMessage = showMessage
    },
    dismissClippy(message){
      this.clipMessage = message
      setTimeout( () => this.shown = false, 1000)
    },
  },
}
</script>

<style lang="stylus">
#clippy
  box-sizing: border-box
  position absolute
  z-index 100
  min-height 300px
  min-width 300px
  bottom 0
  right 0
  perspective 40vmin
  padding 20px
  #clip-holder
    position absolute
    width 90%
    object-fit contain
    transition .7s cubic-bezier(0.680, -0.550, 0.375, 0.885)
    transform skewX(-80deg) translateX(300%) 
    &.introduction
      transform-origin right
      animation clippy-in .7s 1.5s cubic-bezier(0.725, 0.025, 0.230, 1.515) forwards
      #the-clipman-himself
        animation: wobble-hor-bottom 4s 3s ease infinite
    &.exiting
      transform-origin right
      animation clippy-out .7s 0s cubic-bezier(0.725, 0.025, 0.230, 1.515) forwards
  #clippy-modal
    position absolute
    top -30%
    width 80%
    text-align center
    background lightyellow
    border-radius 10px
    padding 10px
    opacity 0
    animation clippy-message .3s 3s cubic-bezier(0.790, 0.265, 0.265, 1.550) forwards
    filter drop-shadow(5px 5px 0px #e8db8788)
    &.exiting
      animation clippy-message-out .3s 0s cubic-bezier(0.790, 0.265, 0.265, 1.550) forwards

    &::after
      content ''
      background lightyellow
      height 20px
      width 40px
      position: absolute;
      left: 50%;
      
      transform: translateX(-50%);
      clip-path: polygon(50% 100%, 0 0, 100% 0);

// reverse keyword wasn't working and I wasn't about to spend time figuring it out  
// so here's two of each
@keyframes clippy-in {
0%  {
  transform skewX(-80deg) rotate(-20deg) translateX(300%) 
}
100%{
  transform skewX(0deg) rotate(0deg)  translateX(0%) 
}}  
@keyframes clippy-out {
0%  {
  transform skewX(0deg) rotate(0deg)  translateX(0%) 
}
100%{
  transform skewX(-80deg) rotate(-20deg) translateX(300%) 
}}

@keyframes clippy-message {
0%  {
  opacity 0
  transform translateY(100%)
 }
100%{
  opacity 1
  transform translateY(00%)
}}
@keyframes clippy-message-out {
0%  {
  opacity 1
  transform translateY(00%)
 }
100%{
  opacity 0
  transform translateY(100%)
}}

@keyframes wobble-hor-bottom {
  0%,
  100% {
    transform: translateX(0%);
    transform-origin: 90% 100%;
  }
  3.75% {
    transform: translateX(-30px) rotate(-6deg);
    transform-origin: 10% 100%;
  }
  7.5% {
    transform: translateX(15px) rotate(6deg);
    transform-origin: 90% 100%;
  }
  11.25% {
    transform: translateX(-15px) rotate(-3.6deg);
    transform-origin: 10% 100%;
  }
  15% {
    transform: translateX(9px) rotate(2.4deg);
    transform-origin: 90% 100%;
  }
  18.75% {
    transform: translateX(-6px) rotate(-1.2deg);
    transform-origin: 10% 100%;
  }
  22.5% {
    transform: translateX(0%);
    transform-origin: 90% 100%;
  }
}
/* ----------------------------------------------
 * Generated by Animista on 2019-10-4 14:20:29
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */
</style>